### PR TITLE
Changed to allow phpunit.xml file in project root.

### PR DESCRIPTION
**Pull request by joachim-n**

### CODE REVIEW

**Comment by AKocherhin** [comment]
Hi @joachim-n 
Might be better put "Allow phpunit.xml file in project root" into its own command
And we can call i something like 
`ddev phpunit_root`

or use some another flag for example --root_conf
What do you think?

**Comment by joachim-n** [comment]
I think it's better UX if it's automatic.

I don't think a separate command or a flag makes sense -- you either have it set up with phpunit.xml in the root, or you're using the one in core, and it's like that for your project all the time.

**Comment by AKocherhin** [comment]
ok. I agree.
in this case, we need changes in documentations too. 
Could you please add?

**Comment by justafish** [comment]
Thanks for the PR @joachim-n  - `core/phpunit.xml` is already used by this project and gitignored, so you're welcome to modify it for your own purposes or run `ddev exec phpunit` for your own custom flags.

**Pull request closed without merging**
